#!/usr/bin/env python3
import os

# Required CGI headers (status and content-type)
print("Status: 200 OK")
print("Content-Type: text/html\r\n")  # \r\n marks the end of headers

# HTML response body
print("""
<!DOCTYPE html>
<html>
<head>
    <title>CGI Test</title>
</head>
<body>
    <h1>CGI Test Successful!</h1>
    <p>This response was generated by a Python CGI script.</p>
    <p>Environment Variables:</p>
    <ul>
        <li><strong>REQUEST_METHOD:</strong> {}</li>
        <li><strong>QUERY_STRING:</strong> {}</li>
        <li><strong>SCRIPT_NAME:</strong> {}</li>
    </ul>
</body>
</html>
""".format(
    os.environ.get("REQUEST_METHOD", "N/A"),
    os.environ.get("QUERY_STRING", "N/A"),
    os.environ.get("SCRIPT_NAME", "N/A")
))